### ISSUE TITLE
Validate TransferRequest reference

### ISSUE THREAD

**Issue by imetaxas** [imetaxas/double-entry-bookkeeping-api#15]
Throw a proper exception message:

at com.yanimetaxas.bookkeeping.dao.TransactionDaoImpl.storeTransaction(TransactionDaoImpl.java:42)
	at com.yanimetaxas.bookkeeping.service.TransferServiceImpl.storeTransaction(TransferServiceImpl.java:56)
	at com.yanimetaxas.bookkeeping.service.TransferServiceImpl.transferFunds(TransferServiceImpl.java:40)
	at com.yanimetaxas.bookkeeping.model.Ledger.commit(Ledger.java:36)
	at com.yanimetaxas.bookkeeping.model.LedgerTest.accountBalancesUpdatedAfterTransferUsingJdbcMysql(LedgerTest.java:216)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'Client_1530466126023-T1' for key 'PRIMARY'

Schema:
PRIMARY KEY(client_ref, transaction_ref)

**Comment by imetaxas** [comment]
Done and tested
